### ISSUE TITLE
Оптимизация игры

### ISSUE THREAD

**Issue by WRONGI1** [softbie/hardtime-rebirth#11]
Было бы замечательно добавить возможность расширить разрешение хотя бы до 2к, а также убрать проблему низкого фпс при полноэкранном режиме. Думаю, этот баг можно решить, ведь фпс перестает быть на минимальных значениях, если игра сворачивается и открывается заново.

**Comment by 13Hz** [comment]
Проблему ФПС'а никак не устранить непосредственно из кода игры, дело на уровне самого движка. Единственное, что могу подсказать для решения проблемы с низким фпсом - https://github.com/dege-diosg/dgVoodoo2
